# Simple test sweep configuration
name: "Test Sweep"
program: simple_test.py
project: "csi-predictor"
entity: "tony-vallad-chru-de-nancy"
method: random
metric:
  name: val_f1_weighted
  goal: maximize

parameters:
  learning_rate:
    values: [0.001, 0.01, 0.1]
  batch_size:
    values: [16, 32, 64] 