# W&B Sweep Configuration for CSI-Predictor - ResNet50
# This file defines the hyperparameter search space for ResNet50 model optimization

name: "CSI-Predictor ResNet50 Hyperparameter Optimization"
program: sweep_train.py
project: "csi-predictor"
entity: "tony-vallad-chru-de-nancy"
method: bayes
metric:
  name: val_f1_weighted
  goal: maximize

parameters:
  # Fixed model parameters
  model_arch:
    value: 'resnet50'
  
  # Fixed preprocessing parameters
  use_official_processor:
    value: false
  
  # Fixed batch size for ResNet50
  batch_size:
    value: 128
  
  # Optimizer settings
  optimizer:
    values: ['adam', 'adamw', 'sgd']
  
  # Learning rate - ResNet50 often benefits from higher learning rates
  learning_rate:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.01
  
  # Weight decay
  weight_decay:
    distribution: log_uniform_values
    min: 0.000001
    max: 0.001
  
  # Dropout rate
  dropout_rate:
    distribution: uniform
    min: 0.1
    max: 0.7
  
  # Momentum (for SGD)
  momentum:
    distribution: uniform
    min: 0.8
    max: 0.99
  
  # Normalization strategy
  normalization_strategy:
    values: ['imagenet', 'medical']
  
  # Scheduler type
  scheduler_type:
    values: ['ReduceLROnPlateau', 'CosineAnnealingLR']
  
  # Loss function weights for class imbalance
  unknown_weight:
    distribution: uniform
    min: 0.1
    max: 1.0
  
  # Early stopping patience
  patience:
    value: 15

# Early termination for poor performing runs
early_terminate:
  type: hyperband
  min_iter: 5
  eta: 3 